on: [push]
name: Test Docker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Build Docker image
        run: docker build -t api .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 api

      - name: Test API
        run: curl -s http://localhost:8080/by-search-term/avicii
